## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Nissisoft"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/yancy-min-842ofHC6MaI-unsplash.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/rubot99"
  twitter = "https://twitter.com/rubot99"
#  email = "caressofsteel@protonmail.com"
#  instagram = "https://instagram.com"
#  linkedin = "https://linkedin.com"
#  telegram = "https://telegram.org"